### ISSUE TITLE
Overrides not supported due to API version

### ISSUE THREAD

**Issue by chris-dnv** [Azure/manage-azure-policy#100] opened 2024-01-04 08:19 UTC
I'm getting the following error when an assignment has overrides added, can this be fixed please?

assignment. Error: The property 'overrides' 
is not supported in API version '2021-06-01'.
Please use API version '2022-06-01' or higher.

**Comment by o-l-a-v** [comment] 2024-02-21 18:18
Duplicate of #98.

**Closed** 2024-03-28 20:37 UTC
Labels: need-to-triage
