### ISSUE TITLE
Incremental mode not working?

### ISSUE THREAD

**Issue by jesseloudon** [Azure/manage-azure-policy#29] opened 2020-10-25 02:14 UTC
https://github.com/Azure/manage-azure-policy#inputs-for-the-action states that incremental mode is doing a comparison of the policy states and making changes to the Azure version if there is a mismatch.

I've exported a policy to GH, then changed the policy definition slightly from Azure, then when running the GHA workflow it didn't detect I made a change to the Azure definition and no sync/overwrite was made from GH.

**Comment by raiyanalam** [comment] 2020-10-26 14:47
As mentioned in the email, this is not an expected behaviour. We want to investigate this further. Please email us what you modified in the policy definition so that we can reproduce this.

**Comment by rgsubh** [comment] 2020-10-28 05:01
@ajinkya599 Looks like path parsing, can you please have a look?

**Comment by ajinkya599** [comment] 2020-12-04 07:44
Closing as discussed over email.

This behavior is as per the current design. We use a `hash` property in policy metadata to verify whether there is any change in policy-in-code. The logic is - "Policy is considered to be changed in code if the calculated hash of `policy.json` differs from the hash present in Azure". So, the change in remote policy does not get detected by the action as when you are modifying the policy from the portal, the hash remains unchanged.

There is an option to give `mode = COMPLETE` to always sync policy from code to Azure.

**Closed by ajinkya599** 2020-12-04 07:44 UTC
Labels: bug
